#!/bin/bash

CORE_JS_VERSION=`node echoPackageVersion.js node_modules/babel-core/node_modules/core-js/package.json`

[ ! -d lib ] && mkdir lib

if [ ! -f lib/core-js-no-number-${CORE_JS_VERSION}.js ]
then
  echo Building core-js@${CORE_JS_VERSION} without ES6 number constructor...
  cd node_modules/babel-core/node_modules/core-js
  npm install
  cd ../../../..
  npm run build-core-js
  mv node_modules/babel-core/node_modules/core-js/core-js-no-number.js lib/core-js-no-number-${CORE_JS_VERSION}.js
  cd lib
  ln -sf core-js-no-number-${CORE_JS_VERSION}.js core-js-no-number.js
else
  echo core-js@${CORE_JS_VERSION} without ES6 number constructor is up to date.
fi
