#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

WEBPACK_DIR="$SCRIPTPATH/webpack"
LIB_DIR="$WEBPACK_DIR/lib"

CORE_JS_VERSION=`node echoPackageVersion.js node_modules/core-js/package.json`

[ ! -d "$LIB_DIR" ] && mkdir "$LIB_DIR"

if [ ! -f "$LIB_DIR/core-js-no-number-${CORE_JS_VERSION}.js" ]
then
  echo Building core-js@${CORE_JS_VERSION} without ES6 number constructor...
  cd node_modules/core-js
  npm install
  cd "$SCRIPTPATH"
  npm run build-core-js
  mv node_modules/core-js/core-js-no-number.js "$LIB_DIR/core-js-no-number-${CORE_JS_VERSION}.js"
  cd "$LIB_DIR"
  ln -sf core-js-no-number-${CORE_JS_VERSION}.js core-js-no-number.js
else
  echo core-js@${CORE_JS_VERSION} without ES6 number constructor is up to date.
fi
