#!/bin/sh

cd webpack
rm -rvf assets
(
  node-inspector &
  ../node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.config.client.dev.js --progress --colors &
  ../node_modules/webpack/bin/webpack.js --config webpack.config.server.js --watch &

  # wait for server bundle to be output
  (while : ; do
    [ -f 'assets/server.bundle.js' ] && break
    sleep 1
  done) &&

  cd ../meteor_core &&
  ([ ! -d prod ] || mv prod .prod) &&
  ([ ! -d .dev ] || mv .dev dev  ) &&
  export NODE_OPTIONS='--debug=5858' &&
  meteor --settings ../settings/devel.json &
) | cat
