#!/bin/bash

./core-js-custom-build

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

WEBPACK_DIR=$SCRIPTPATH/webpack
METEOR_DIR=$SCRIPTPATH/meteor_core

[ -f $METEOR_DIR/client/client.bundle.js ] && rm $METEOR_DIR/client/client.bundle.js
[ -f $METEOR_DIR/server/server.bundle.js ] && rm $METEOR_DIR/server/server.bundle.js

cd $WEBPACK_DIR
rm -rf assets
(
  node-inspector &
  $SCRIPTPATH/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.config.client.dev.js --progress --colors &
  $SCRIPTPATH/node_modules/webpack/bin/webpack.js --config webpack.config.server.dev.js --progress --colors --watch &

  # wait for server bundle to be output
  SERVER_BUNDLE="assets/server.bundle.js"
  (while : ; do
    [ -f "$SERVER_BUNDLE" ] && break
    sleep 1
  done) &&

  cd $METEOR_DIR
  echo "Npm.require('$WEBPACK_DIR/$SERVER_BUNDLE');" > server/require-server-bundle.js
  ln -sf $WEBPACK_DIR/loadClientBundle.html client/loadClientBundle.html &&
  export NODE_OPTIONS='--debug=5858' &&
  meteor --settings ../settings/devel.json &
) | cat


