#!/bin/bash

echo
echo Building webpack bundles for deployment...
echo
./predeploy

if [[ $1 == *"meteor.com" ]]
then
  cd meteor_core
  meteor deploy $1
else
  case $1 in
      "modulus" )
        env set METEOR_SETTINGS "$(cat settings/prod.json)"
        cd meteor_core
        modulus deploy --project-name your_app_proj_name
      ;;

      "mup" )
        echo "Make sure to mup init and mup setup before first deploy"
        # you will also need to move settings/prod.json to settings/prod/settings.json
        # then mup init inside settings/prod/ so that mup uses the new settings.json
        # this will require a settings path change in ./dev script
        mup deploy
      ;;

      "demeteorizer" )
        echo "Building meteor bundle..."
        rm -rvf dist/bundle
        mkdir -p dist/bundle
        cd meteor_core
        demeteorizer -o ../dist/bundle --json "$(cat settings/prod.json)"
        # run your own command to deploy to your server
      ;;

      * )
        echo "See deploy file to customize your deploy command"
      ;;
  esac
fi