#!/bin/bash

./core-js-custom-build

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

WEBPACK_DIR=$SCRIPTPATH/webpack
METEOR_DIR=$SCRIPTPATH/meteor_core

[ -f $METEOR_DIR/client/loadClientBundle.html ] && rm $METEOR_DIR/client/loadClientBundle.html
[ -f $METEOR_DIR/server/require-server-bundle.js ] && rm $METEOR_DIR/server/require-server-bundle.js

cd $WEBPACK_DIR
env NODE_ENV=production $SCRIPTPATH/node_modules/webpack/bin/webpack.js --config webpack.config.client.prod.js --progress --colors
env NODE_ENV=production $SCRIPTPATH/node_modules/webpack/bin/webpack.js --config webpack.config.server.prod.js --progress --colors
cd $METEOR_DIR
SERVER_BUNDLE="assets/server.bundle.js"
CLIENT_BUNDLE="assets/client.bundle.js"
ln -sf $WEBPACK_DIR/$SERVER_BUNDLE server/server.bundle.js
ln -sf $WEBPACK_DIR/$CLIENT_BUNDLE client/client.bundle.js
rm -rf ../dist
METEOR_SETTINGS=$(cat ../settings/prod.json) && meteor build ../dist
