#!/bin/bash

./core-js-custom-build

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

WEBPACK_DIR=$SCRIPTPATH/webpack
METEOR_DIR=$SCRIPTPATH/meteor_core

[ -f $METEOR_DIR/client/loadClientBundle.html ] && rm $METEOR_DIR/client/loadClientBundle.html

cd $WEBPACK_DIR
rm -rvf assets
(
  env NODE_ENV=production ../node_modules/webpack/bin/webpack.js --config webpack.config.client.prod.js --progress --colors --watch &
  env NODE_ENV=production  ../node_modules/webpack/bin/webpack.js --config webpack.config.server.prod.js --progress --colors --watch &

  # wait for bundles to be created
  SERVER_BUNDLE="assets/server.bundle.js"
  CLIENT_BUNDLE="assets/client.bundle.js"
  (while : ; do
    [ -f "$SERVER_BUNDLE" ] && [ -f "$CLIENT_BUNDLE" ] && break
    sleep 1
  done) &&

  cd $METEOR_DIR
  ln -sf $WEBPACK_DIR/$SERVER_BUNDLE server/server.bundle.js &&
  ln -sf $WEBPACK_DIR/$CLIENT_BUNDLE client/client.bundle.js &&
  meteor run --production --settings ../settings/prod.json &
) | cat
